### ISSUE TITLE
Unable to clear date.

### ISSUE THREAD

**Issue by prettyboymp** [voceconnect/voce-post-meta-date#14]
It looks like updateLimits is causing the date to be validated even when it's just the default text.  This is causing:
1. The date selection to automatically open on page load
2. Clicking 'Done' to select the current date instead of allowing it to stay the default text/empty value
3. Cilckcing clear to select the current date instead of clearing the value.

**Comment by banderon** [comment]
There's a few bugs with the timepicker.js lib that was used. We need to replace it with a newer library.

**Comment by kevinlangleyjr** [comment]
Seems this has actually been fixed.
